version: "3.7"
services:
  homepage:
    image: docker-sio-releases.seikatsu.io/homepage:latest
    container_name: homepage
    restart: always
    networks:
      dockerized:
        aliases:
          - homepage.docker.local
networks:
  dockerized:
    external: true
