version: '3.7'
services:
  homepage:
    image: ghcr.io/seiikatsu/homepage:latest
    ports:
      - "3000:3000"
    environment:
        - MAIL_SERVER_HOST=
        - MAIL_SERVER_PORT=
        - MAIL_SERVER_RECEIVER=
        - MAIL_SERVER_USER=
        - MAIL_SERVER_PASSWORD=
