name: '📦 Build and publish'

permissions:
  contents: read
  packages: write

env:
  # see https://github.com/orgs/community/discussions/45969
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

on:
  release:
    types: [published]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64,linux/amd64
          cache-from: 'type=gha'
          cache-to: 'type=gha,mode=max'
          push: true
          provenance: false
          tags: ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }},ghcr.io/${{ github.repository }}:latest
